services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/configs:/app/configs
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

    command: ["npm", "run", "dev"]
    environment:
      - REACT_APP_API_URL=http://localhost:8000
