"""migration2

Revision ID: 05f0b12c4479
Revises: 16c76fba4401
Create Date: 2025-05-12 22:53:38.025193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '05f0b12c4479'
down_revision: Union[str, None] = '16c76fba4401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_types')
    op.drop_index('ix_mcp_agents_id', table_name='mcp_agents')
    op.drop_index('ix_mcp_agents_name', table_name='mcp_agents')
    op.drop_table('mcp_agents')
    op.drop_index('ix_agent_files_id', table_name='agent_files')
    op.drop_table('agent_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('mcp_agents', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agent_files_id', 'agent_files', ['id'], unique=False)
    op.create_table('mcp_agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=False),
    sa.Column('command', sa.VARCHAR(), nullable=False),
    sa.Column('args', sqlite.JSON(), nullable=False),
    sa.Column('env', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_mcp_agents_name', 'mcp_agents', ['name'], unique=1)
    op.create_index('ix_mcp_agents_id', 'mcp_agents', ['id'], unique=False)
    op.create_table('agent_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('command', sa.VARCHAR(), nullable=False),
    sa.Column('args', sqlite.JSON(), nullable=False),
    sa.Column('env_keys', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
