"""Initial migration

Revision ID: 83082d131e5a
Revises: 
Create Date: 2025-05-12 21:01:44.465449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '83082d131e5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mcp_agents_id', table_name='mcp_agents')
    op.drop_index('ix_mcp_agents_name', table_name='mcp_agents')
    op.drop_table('mcp_agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=False),
    sa.Column('command', sa.VARCHAR(), nullable=False),
    sa.Column('args', sqlite.JSON(), nullable=False),
    sa.Column('env', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcp_agents_name', 'mcp_agents', ['name'], unique=1)
    op.create_index('ix_mcp_agents_id', 'mcp_agents', ['id'], unique=False)
    # ### end Alembic commands ###
